

# This file was *autogenerated* from the file fox_milnor_test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1)
import snappy
from snappy.snap.fox_milnor import alexander_data
import pandas as pd
import numpy as np

df = pd.read_csv('/Users/seohyeonlee/knotinfo/results/mod32_applied.csv')

fox_milnor_failed = []

def apply_fox_milnor_test(row):
	try:
		linkname = row['name_unoriented']
		M = snappy.Manifold(linkname)
		row['fox_milnor_test'] = M.fox_milnor_test()
		print(M.fox_milnor_test() )
	except:
		print(f'unable to apply fox milnor test to {linkname}')
		row['fox_milnor_test'] = np.nan
		fox_milnor_failed.append(linkname)
	return row['fox_milnor_test']

df['fox_milnor_test'] = df.apply(apply_fox_milnor_test, axis=_sage_const_1 )

fox_applied = df[df['fox_milnor_test']]

fox_applied.to_csv('/Users/seohyeonlee/knotinfo/results/fox_milnor_applied.csv')

